name: 'Infra Cost'
description: 'Comprehensive cost analysis and infrastructure optimization across AWS, GCP, Azure, Alibaba Cloud, and Oracle Cloud'
author: 'Code Collab'

branding:
  icon: 'dollar-sign'
  color: 'green'

inputs:
  # Cloud Provider Configuration
  provider:
    description: 'Cloud provider (aws, gcp, azure, alicloud, oracle)'
    required: false
    default: 'aws'

  profile:
    description: 'Cloud provider profile to use'
    required: false
    default: 'default'

  region:
    description: 'Cloud provider region'
    required: false
    default: 'us-east-1'

  # AWS Credentials
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: false

  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: false

  aws-session-token:
    description: 'AWS Session Token (for temporary credentials)'
    required: false

  # GCP Credentials
  gcp-project-id:
    description: 'GCP Project ID'
    required: false

  gcp-key-file:
    description: 'Path to GCP service account key file'
    required: false

  # Azure Credentials
  azure-subscription-id:
    description: 'Azure Subscription ID'
    required: false

  azure-tenant-id:
    description: 'Azure Tenant ID'
    required: false

  azure-client-id:
    description: 'Azure Client ID'
    required: false

  azure-client-secret:
    description: 'Azure Client Secret'
    required: false

  # Analysis Options
  command:
    description: 'Command to run (now, free-tier, annotate, dashboard, history, blame, cost, optimize, monitor, export)'
    required: false
    default: 'now'

  subcommand:
    description: 'Subcommand for nested commands (e.g., cost breakdown, optimize recommendations)'
    required: false

  forecast-days:
    description: 'Number of days for cost forecast (default: 30)'
    required: false
    default: '30'

  trend-months:
    description: 'Number of months for trend analysis (default: 6)'
    required: false
    default: '6'

  # Cost Gates
  fail-on-increase:
    description: 'Fail if costs increased compared to previous period (true/false)'
    required: false
    default: 'false'

  cost-threshold:
    description: 'Maximum acceptable cost (e.g., 1000 for $1000/month)'
    required: false

  # Output Options
  output-format:
    description: 'Output format (text, json)'
    required: false
    default: 'text'

  export-format:
    description: 'Export format for reports (json, csv, xlsx)'
    required: false

  # Alerting
  budget-threshold:
    description: 'Budget threshold for alerts (e.g., 1000 for $1000)'
    required: false

  delta-threshold:
    description: 'Alert threshold for cost changes in percentage (default: 10)'
    required: false
    default: '10'

  # Notifications
  slack-webhook:
    description: 'Slack webhook URL for notifications'
    required: false

  slack-channel:
    description: 'Slack channel for notifications'
    required: false

  # PR Comment
  comment-on-pr:
    description: 'Post cost analysis as PR comment (true/false)'
    required: false
    default: 'false'

  fail-on-threshold:
    description: 'Fail the action if costs exceed threshold (true/false)'
    required: false
    default: 'false'

  # Additional CLI arguments
  additional-args:
    description: 'Additional CLI arguments to pass to infra-cost'
    required: false

outputs:
  today-cost:
    description: 'Cost for today'

  mtd-cost:
    description: 'Month-to-date cost'

  ytd-cost:
    description: 'Year-to-date cost'

  total-cost:
    description: 'Total cost for the analysis period'

  cost-change:
    description: 'Cost change compared to previous period'

  cost-change-percent:
    description: 'Cost change percentage compared to previous period'

  forecast-cost:
    description: 'Forecasted cost for the specified period'

  anomalies-detected:
    description: 'Number of cost anomalies detected'

  optimization-savings:
    description: 'Potential savings from optimization recommendations'

  free-tier-usage:
    description: 'Free tier usage percentage'

  report-json:
    description: 'Full report in JSON format'

  exit-code:
    description: 'Exit code of the analysis (0 = success, 1 = threshold exceeded)'

  threshold-exceeded:
    description: 'Whether cost threshold was exceeded (true/false)'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install infra-cost
      shell: bash
      run: npm install -g infra-cost@${{ github.action_ref || 'latest' }}

    - name: Run Cost Analysis
      id: analysis
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_SESSION_TOKEN: ${{ inputs.aws-session-token }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ inputs.gcp-key-file }}
        AZURE_SUBSCRIPTION_ID: ${{ inputs.azure-subscription-id }}
        AZURE_TENANT_ID: ${{ inputs.azure-tenant-id }}
        AZURE_CLIENT_ID: ${{ inputs.azure-client-id }}
        AZURE_CLIENT_SECRET: ${{ inputs.azure-client-secret }}
      run: |
        # Build the command with new subcommand structure
        CMD="infra-cost"

        # Add command (defaults to 'now' for quick cost check)
        CMD="$CMD ${{ inputs.command }}"

        # Add subcommand if specified
        if [ -n "${{ inputs.subcommand }}" ]; then
          CMD="$CMD ${{ inputs.subcommand }}"
        fi

        # Add global options
        CMD="$CMD --provider ${{ inputs.provider }}"

        # Add profile if specified
        if [ -n "${{ inputs.profile }}" ] && [ "${{ inputs.profile }}" != "default" ]; then
          CMD="$CMD --profile ${{ inputs.profile }}"
        fi

        # Add region
        CMD="$CMD --region ${{ inputs.region }}"

        # Add output format
        CMD="$CMD --output ${{ inputs.output-format }}"

        # Add GCP project ID
        if [ -n "${{ inputs.gcp-project-id }}" ]; then
          CMD="$CMD --project-id ${{ inputs.gcp-project-id }}"
        fi

        # Add command-specific options
        case "${{ inputs.command }}" in
          "cost")
            if [ -n "${{ inputs.forecast-days }}" ]; then
              CMD="$CMD --forecast-days ${{ inputs.forecast-days }}"
            fi
            ;;
          "monitor")
            if [ -n "${{ inputs.delta-threshold }}" ]; then
              CMD="$CMD --threshold ${{ inputs.delta-threshold }}"
            fi
            ;;
          "export")
            if [ -n "${{ inputs.export-format }}" ]; then
              CMD="$CMD --format ${{ inputs.export-format }}"
            fi
            ;;
        esac

        # Add additional arguments
        if [ -n "${{ inputs.additional-args }}" ]; then
          CMD="$CMD ${{ inputs.additional-args }}"
        fi

        echo "Running: $CMD"

        # Run the analysis and capture output
        OUTPUT_FILE=$(mktemp)
        JSON_OUTPUT=$(mktemp)
        set +e

        # Run command with JSON output for parsing
        if [ "${{ inputs.output-format }}" = "json" ]; then
          $CMD > "$OUTPUT_FILE" 2>&1
          EXIT_CODE=$?
          cp "$OUTPUT_FILE" "$JSON_OUTPUT"
        else
          # Run twice: once for display, once for JSON parsing
          $CMD > "$OUTPUT_FILE" 2>&1
          EXIT_CODE=$?
          $CMD --output json > "$JSON_OUTPUT" 2>&1 || true
        fi
        set -e

        # Display output
        cat "$OUTPUT_FILE"

        # Parse JSON output for structured data
        if [ -f "$JSON_OUTPUT" ] && [ -s "$JSON_OUTPUT" ]; then
          # Extract cost metrics using jq if available
          if command -v jq &> /dev/null; then
            TODAY_COST=$(jq -r '.todayCost // .currentCost // "0"' "$JSON_OUTPUT" 2>/dev/null || echo "0")
            MTD_COST=$(jq -r '.mtdCost // .monthToDate // "0"' "$JSON_OUTPUT" 2>/dev/null || echo "0")
            YTD_COST=$(jq -r '.ytdCost // .yearToDate // "0"' "$JSON_OUTPUT" 2>/dev/null || echo "0")
            TOTAL_COST=$(jq -r '.totalCost // .total // "0"' "$JSON_OUTPUT" 2>/dev/null || echo "0")
            COST_CHANGE=$(jq -r '.costChange // .change // "0"' "$JSON_OUTPUT" 2>/dev/null || echo "0")
            COST_CHANGE_PERCENT=$(jq -r '.costChangePercent // .changePercent // "0"' "$JSON_OUTPUT" 2>/dev/null || echo "0")
            FREE_TIER_USAGE=$(jq -r '.freeTierUsage // "0"' "$JSON_OUTPUT" 2>/dev/null || echo "0")
            OPTIMIZATION_SAVINGS=$(jq -r '.optimizationSavings // .potentialSavings // "0"' "$JSON_OUTPUT" 2>/dev/null || echo "0")

            echo "today-cost=$TODAY_COST" >> $GITHUB_OUTPUT
            echo "mtd-cost=$MTD_COST" >> $GITHUB_OUTPUT
            echo "ytd-cost=$YTD_COST" >> $GITHUB_OUTPUT
            echo "total-cost=$TOTAL_COST" >> $GITHUB_OUTPUT
            echo "cost-change=$COST_CHANGE" >> $GITHUB_OUTPUT
            echo "cost-change-percent=$COST_CHANGE_PERCENT" >> $GITHUB_OUTPUT
            echo "free-tier-usage=$FREE_TIER_USAGE" >> $GITHUB_OUTPUT
            echo "optimization-savings=$OPTIMIZATION_SAVINGS" >> $GITHUB_OUTPUT
          fi

          # Store full JSON report
          echo "report-json=$(cat "$JSON_OUTPUT" | tr -d '\n')" >> $GITHUB_OUTPUT
        fi

        echo "exit-code=$EXIT_CODE" >> $GITHUB_OUTPUT

        # Check cost gates
        THRESHOLD_EXCEEDED="false"

        # Check cost threshold if specified
        if [ -n "${{ inputs.cost-threshold }}" ] && command -v jq &> /dev/null; then
          CURRENT_COST=$(jq -r '.totalCost // .mtdCost // "0"' "$JSON_OUTPUT" 2>/dev/null || echo "0")
          THRESHOLD="${{ inputs.cost-threshold }}"

          if (( $(echo "$CURRENT_COST > $THRESHOLD" | bc -l) )); then
            echo "::warning::Cost threshold exceeded: \$$CURRENT_COST > \$$THRESHOLD"
            THRESHOLD_EXCEEDED="true"

            if [ "${{ inputs.fail-on-threshold }}" = "true" ]; then
              echo "::error::Failing due to cost threshold exceeded"
              EXIT_CODE=1
            fi
          fi
        fi

        # Check cost increase if enabled
        if [ "${{ inputs.fail-on-increase }}" = "true" ] && command -v jq &> /dev/null; then
          COST_CHANGE=$(jq -r '.costChange // "0"' "$JSON_OUTPUT" 2>/dev/null || echo "0")

          if (( $(echo "$COST_CHANGE > 0" | bc -l) )); then
            echo "::warning::Cost increased by \$$COST_CHANGE"
            THRESHOLD_EXCEEDED="true"
            echo "::error::Failing due to cost increase detected"
            EXIT_CODE=1
          fi
        fi

        echo "threshold-exceeded=$THRESHOLD_EXCEEDED" >> $GITHUB_OUTPUT

        # Clean up
        rm -f "$OUTPUT_FILE" "$JSON_OUTPUT"

        # Exit with appropriate code
        if [ $EXIT_CODE -ne 0 ]; then
          exit $EXIT_CODE
        fi

    - name: Comment on PR
      if: inputs.comment-on-pr == 'true' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');

          // Get outputs from analysis step
          const todayCost = '${{ steps.analysis.outputs.today-cost }}' || 'N/A';
          const mtdCost = '${{ steps.analysis.outputs.mtd-cost }}' || 'N/A';
          const totalCost = '${{ steps.analysis.outputs.total-cost }}' || 'N/A';
          const costChange = '${{ steps.analysis.outputs.cost-change }}' || '0';
          const costChangePercent = '${{ steps.analysis.outputs.cost-change-percent }}' || '0';
          const freeTierUsage = '${{ steps.analysis.outputs.free-tier-usage }}' || 'N/A';
          const optimizationSavings = '${{ steps.analysis.outputs.optimization-savings }}' || '0';
          const thresholdExceeded = '${{ steps.analysis.outputs.threshold-exceeded }}' === 'true';

          // Determine status emoji
          let statusEmoji = '✅';
          if (thresholdExceeded) {
            statusEmoji = '❌';
          } else if (parseFloat(costChange) > 0) {
            statusEmoji = '⚠️';
          }

          // Build comment body
          let body = `## ${statusEmoji} Infra Cost Analysis\n\n`;

          // Cost Summary Table
          body += '### 📊 Cost Summary\n\n';
          body += '| Metric | Value |\n';
          body += '|--------|-------|\n';
          body += `| **Today's Cost** | \$${todayCost} |\n`;
          body += `| **Month-to-Date** | \$${mtdCost} |\n`;
          body += `| **Total Cost** | \$${totalCost} |\n`;

          if (parseFloat(costChange) !== 0) {
            const changeSymbol = parseFloat(costChange) > 0 ? '📈' : '📉';
            body += `| **Cost Change** | ${changeSymbol} \$${costChange} (${costChangePercent}%) |\n`;
          }

          if (freeTierUsage !== 'N/A') {
            body += `| **Free Tier Usage** | ${freeTierUsage}% |\n`;
          }

          if (parseFloat(optimizationSavings) > 0) {
            body += `| **Optimization Potential** | 💡 \$${optimizationSavings}/month |\n`;
          }

          body += '\n';

          // Threshold Warning
          if (thresholdExceeded) {
            body += '### ❌ Cost Gate Failed\n\n';
            if ('${{ inputs.cost-threshold }}') {
              body += `Cost threshold of \$${{ inputs.cost-threshold }} has been exceeded.\n\n`;
            }
            if ('${{ inputs.fail-on-increase }}' === 'true' && parseFloat(costChange) > 0) {
              body += `Cost has increased by \$${costChange}.\n\n`;
            }
          } else if (parseFloat(costChange) > 0) {
            body += '### ⚠️ Cost Increase Detected\n\n';
            body += `Costs have increased by \$${costChange} (${costChangePercent}%).\n\n`;
          }

          // Configuration Details
          body += '<details><summary>📋 Configuration</summary>\n\n';
          body += '| Setting | Value |\n';
          body += '|---------|-------|\n';
          body += `| Provider | ${{ inputs.provider }} |\n`;
          body += `| Region | ${{ inputs.region }} |\n`;
          body += `| Command | \`${{ inputs.command }}\` |\n`;
          if ('${{ inputs.subcommand }}') {
            body += `| Subcommand | \`${{ inputs.subcommand }}\` |\n`;
          }
          if ('${{ inputs.cost-threshold }}') {
            body += `| Cost Threshold | \$${{ inputs.cost-threshold }} |\n`;
          }
          body += `| Fail on Increase | ${{ inputs.fail-on-increase }} |\n`;
          body += `| Fail on Threshold | ${{ inputs.fail-on-threshold }} |\n`;
          body += '</details>\n\n';

          // Full Report
          const reportJson = '${{ steps.analysis.outputs.report-json }}';
          if (reportJson && reportJson !== '') {
            body += '<details><summary>📄 Full Report (JSON)</summary>\n\n';
            body += '```json\n';
            try {
              body += JSON.stringify(JSON.parse(reportJson), null, 2);
            } catch (e) {
              body += reportJson;
            }
            body += '\n```\n</details>\n\n';
          }

          body += '---\n';
          body += '*Generated by [infra-cost](https://github.com/codecollab-co/infra-cost) v${{ github.action_ref }}*';

          // Find existing comment
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const botComment = comments.find(comment =>
            comment.user.type === 'Bot' &&
            comment.body.includes('Infra Cost Analysis')
          );

          if (botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: body
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
          }

    - name: Send Slack Notification
      if: inputs.slack-webhook != ''
      shell: bash
      run: |
        curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "💰 Infra Cost Analysis Complete",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "💰 Infra Cost Analysis"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Provider:*\n${{ inputs.provider }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Region:*\n${{ inputs.region }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Analysis:*\n${{ inputs.analysis-type }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\n${{ github.repository }}"
                  }
                ]
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "Triggered by: ${{ github.actor }} | <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
                  }
                ]
              }
            ]
          }' \
          ${{ inputs.slack-webhook }}
