name: 🌐 Cloud Provider Support
description: Request support for a new cloud provider
title: "[Provider]: Add support for "
labels: ["cloud-provider", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for requesting a new cloud provider! This helps us prioritize which providers to support next.

  - type: dropdown
    id: provider
    attributes:
      label: Cloud Provider
      description: Which cloud provider would you like to see supported?
      options:
        - Google Cloud Platform (GCP)
        - Microsoft Azure
        - Alibaba Cloud
        - Oracle Cloud Infrastructure (OCI)
        - IBM Cloud
        - DigitalOcean
        - Linode/Akamai
        - Vultr
        - Scaleway
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: provider-other
    attributes:
      label: Other Provider Details
      description: If you selected "Other", please specify the provider name and details

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe why you need support for this provider
      placeholder: |
        - We use this provider for production workloads
        - Need multi-cloud cost comparison
        - Part of our cloud migration strategy
    validations:
      required: true

  - type: textarea
    id: api-info
    attributes:
      label: Provider API Information
      description: If you know about the provider's cost/billing API, please share details
      placeholder: |
        - API documentation links
        - Authentication methods
        - Cost data availability
        - Rate limits or restrictions

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this provider support to you?
      options:
        - Low - Future consideration
        - Medium - Would be useful
        - High - Important for adoption
        - Critical - Blocking usage
    validations:
      required: true

  - type: textarea
    id: current-solution
    attributes:
      label: Current Solution
      description: How do you currently track costs for this provider?

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I have access to this provider's APIs for testing
        - label: I can provide API documentation or examples
        - label: I'd be willing to help implement this provider
        - label: I can help test the implementation

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that would help with implementation