name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ['enhancement']

body:
- type: 'markdown'
  attributes:
    value: |-
      Thank you for requesting a feature. Please complete the form below so we can triage and prioritize your feature.


- id: 'detailed_feature_description'
  type: 'textarea'
  attributes:
    label: 'Detailed description of feature'
    description: 'Is your feature request related to a problem? Please describe. Include a suitable example if possible.'
    render: 'markdown'

- id: 'solution_description'
  type: 'textarea'
  attributes:
    label: 'Describe the solution you would like'
    description: 'Is your feature request related to a problem? Please describe. Include a suitable example if possible.'
    render: 'markdown'

- id: 'additional'
  type: 'textarea'
  attributes:
    label: 'Additional information'
    description: 'Describe alternatives you have considered:'
